server:
  port: 8761

spring:
  application:
    name: projuris-service-registry

projuris:
  serviceRegistry:
    username: serviceregistry
    password: "projuris123sr"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: 'http://${projuris.serviceRegistry.username}:${projuris.serviceRegistry.password}@localhost:8761/eureka'
    instance:
      hostname: localhost

