server:
  port: 8080

spring:
  application:
    name: projuris-api-gateway
  cloud:
      gateway:
        routes:
          - id: authuser-service
            uri: lb://PROJURIS-AUTHUSER-SERVICE
            predicates:
              - Path=/projuris-authuser/**
          - id: course-service
            uri: lb://PROJURIS-SERVICEORDER-SERVICE
            predicates:
              - Path=/projuris-serviceorder/**
projuris:
  serviceRegistry:
    username: serviceregistry
    password: "projuris123sr"

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${projuris.serviceRegistry.username}:${projuris.serviceRegistry.password}@localhost:8761/eureka'
    instance:
      hostname: localhost






